# This container will connect to the Raspberry Camera
# initial it only shot a picture
version: '3.8'

services:
  python-cam:
    container_name: picam
    privileged: true
    build: .
    restart: unless-stopped
    environment:
      - LD_LIBRARY_PATH=/opt/vc/lib
    devices:
      - /dev/vchiq
    # Weitere Einbindung, nicht erlaubt
    # device_cgroup_rules:
    #  - /dev/vchiq
    ports:
      - 144:80
    volumes:
      - /opt/vc:/opt/vc
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.connect==cam
