version: "3"
services:
  node_delivery:
    image: "arm32v7/node:slim"
    user: "node"
    working_dir: /home/node/app
    #    Im Image beschrieben
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "80"
    command: "npm start"

  node_development:
    image: "arm32v7/node"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose:
      - "80"
    command: "npm start"
