version: '3.8'
services:
  performance: # Berechnungen der Performance auf den Mikrocontrollern
    image: 326567/debian-performance
    container_name: deb-performance
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.test==performance