version: "3.3"
services:
  gpio-default:
    container_name: gpio
    build:
      context: ./
      dockerfile: ./Dockerfile
    deploy:
      placement:
        constraints:
          - node.labels.gpio == default
    devices:
      - /dev/gpiomem -d blink
      - /dev/i2c-1