version: "3.3"
services:
  gpio-default:
    image: 326567/raspberry_gpio_default
    container_name: gpio
    deploy:
      placement:
        constraints:
          - node.labels.gpio == default
    devices:
      - /dev/gpiomem -d blink