# Verbindet den Websocket mit dem Backend
version: '3.8'
services:
  backend:
    container_name: py_backend
    build: ./py_backend
    deploy:
      placement:
        constraints:
          - node.labels.project == visualizer
    volumes:
      - type: volume
        source: data  # volume Name
        target: /data
        volume:
          nocopy: true
    #ports:
    #  - "3000:3000"
    links:
      - "visualiser:vis"

  visualiser:
    container_name: bmp_280_web_visualizer
    build: ./visualizer
    deploy:
      placement:
        constraints:
          - node.labels.project == visualizer
    volumes:
      - /htdocs/ /usr/local/apache2/htdocs/
    ports:
      - "80:80"
      - "433:433"
      - "3000:3000"

volumes:
  data:
