# Verbindet alle bmp280_send und py_backend_1 miteinander
version: '2'
services:
  bmp280:
    container_name: bmp280
    build: ./bmp280_send
    devices:
      - /dev/gpiomem
      - /dev/i2c-1
    volumes_from:
      - data


  visualiser:
    container_name: data_visualizer
    build: visualizer
    volumes_from:
      - data

volumes:
  data: