services:
  nginx_default:
    image: arm32v7/nginx
    container_name: nginx_default
    #build: .
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80