# Anzeige der HTU21D Daten
version: '3.8'

services:
  # Speichert die Daten des HTU in einem volume
  htu_get1:
    container_name: htu_get1
    build: .
    deploy:
      placement:
        constraints:
          - node.labels.project == lc
          - node.hostname == B1
    volumes:
      # GPIO Anbindung
      - /sys/class/gpio/
      # Anbindung der 4 LED Lampen
      - /sys/class/leds/
      # speichern der Daten
      - /htu_data

  # Speichert die Daten des HTU in einem volume
  htu_get2:
    container_name: htu_get2
    build: .
    deploy:
      placement:
        constraints:
          - node.labels.project == lc
          - node.hostname == B2
    volumes:
      # GPIO Anbindung
      - /sys/class/gpio/
      # Anbindung der 4 LED Lampen
      - /sys/class/leds/
      # speichern der Daten
      - /htu_data


  raspi_set:
    # Gibt die HTU21D Daten aus
    container_name: raspi_set
    build: .
    deploy:
      placement:
        constraints:
          - node.labels.project == lc
          - node.hostname == raspi4
    volumes:
      - /htu_data


volumes:
  htu_data:
