# This container will connect to the Raspberry Camera
# test1

version: '3.8'

services:
  python-cam:
    image: # hier muss waas anederes hin
    container_name: pycam
    restart: unless-stopped
    environment:
      - LD_LIBRARY_PATH=/opt/vc/lib

    ports:
      - 144:80
    volumes:
      - /opt/vc:/opt/vc

