version: '3.8'
services:
  python-backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - /data
    container_name: py_backend
    #command: tail -F anything

volumes:
  data:
