# This container will use BeagleBone Black GPIO

version: '3.8'

services:

  bbb_gpio_sh:
    container_name: bbb_sh
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /sys/class/gpio
      - /dev/i2c-0 # P9 I2C PINs
      - /dev/i2c-1
      - /dev/i2c-2
      - gpiochip0
      - gpiochip1
      - gpiochip2
      - gpiochip3
      - /sys/class/leds/beaglebone
