version: "3"
services:
  node_delivery:
    container_name: node
    build: .
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose:
      - "80"
    command: "npm start"

  node_development:
    container_name: node_dev
    build: .
    user: "node"
    environment:
      - NODE_ENV=development
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose:
      - "80"
    command: "npm start"
