# Anzeige der HTU21D Daten
version: '3.8'

services:
  # Speichert die Daten des HTU in einem volume
  htu_get:
    container_name: raspi_send
    build: .
    deploy:
      placement:
        constraints:
          - node.labels.project == lc
    devices:
      # GPIO Anbindung
      - /sys/class/gpio/
      # Anbindung der 4 LED Lampen
      - /sys/class/leds/
    volumes:
      # speichern der Daten
      - /htu_data

volumes:
  htu_data:
