version: '3.8'

services:
  python-pic-save:
    build: .
    volumes:
      - /pictures:/pics
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.connect==cam

volumes:
  pics:
    external: true
