# version: "3.7"
#
#services:
#  service-name:
#    user: seluser:<gid> # required when running in a swarm without sudo - use the <gid> of docker group of swarm
#    hostname: priv_network
#    networks:
#        - priv_network # attachable overlay network to use
#    volumes:
#        - /var/run/docker.sock:/var/run/docker.sock
#    command: ["start", "--swarmOverlayNetwork", "STACK_priv_network", "--videoRecordingEnabled", "false", "--privileged"]
#
#networks:
#    priv_network:
#        driver: overlay
#        attachable: true