version: '3.8'
services:
  python-backend:
    container_name: py_backend
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - /data
    ports:
      - "3000"

volumes:
  data:
