version: '3.8'
services:
  python-backend:
    container_name: py_backend
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - /data
    ports:
      - "3000"
    networks:
      macvlan0:
        ipv4_address: 172.24.0.5 # 3-default

volumes:
  data:

networks:
  macvlan0:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24
          gateway: 172.24.0.1
