version: '3.8'
services:
  bmp280:
    container_name: bmp280
    build: ./bmp280_send
    deploy:
      placement:
        constraints:
          - node.hostname == R3
    devices:
      - /dev/gpiomem
      - /dev/i2c-1
    volumes:
      - type: volume
        source: data
        target: /data
        volume:
          nocopy: true

  visualiser:
    container_name: data_visualizer
    build: ./combined
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname == R3
    volumes:
      - type: bind
        source: /data/
        target: /data

volumes:
  data:
