version: '3.8'
services:
  bmp280:
    container_name: bmp280
    build: ./bmp280_send
    deploy:
      placement:
        constraints:
          - node.hostname == R3
    devices:
      - /dev/
      - /dev/gpiomem
      - /dev/i2c-1
    volumes:
      - /data

  visualiser:
    container_name: data_visualizer
    build: ./combined
    deploy:
      placement:
        constraints:
          - node.hostname == R3
    volumes:
      - /data

volumes:
  data:
