# Verbindet den Websocket miteinander
version: '3.8'
services:
  backend:
    container_name: bmp280_backend
    build: ./web_send
    deploy:
      placement:
        constraints:
          - node.hostname == R3
    volumes:
      - type: volume
        source: data  # volume Name
        target: /data
        volume:
          nocopy: true
    links:
      - "visualiser:vis"

  visualiser:
    container_name: data_visualizer
    build: ./visualizer
    deploy:
      placement:
        constraints:
          - node.hostname == R3

volumes:
  data:
