version: '3.8'
services:
  bmp280:
    container_name: bmp280
    build:
      context: /
      dockerfile: bmp280_send/Dockerfile
    deploy:
      placement:
        constraints:
          - node.hostname == R3
    devices:
      - /dev/
    volumes:
      - data

  visualiser:
    container_name: data_visualizer
    build:
      context: combined/
      dockerfile: combined/Dockerfile
    deploy:
      placement:
        constraints:
          - node.hostname == R3
    volumes:
      - data

volumes:
  data:
