# Speichert die Daten des HTU in einem volume
version: '3.8'
services:
  htu_get:
    container_name: htu_get
    build: .
    deploy:
      placement:
        constraints:
          - node.labels.project == lc
    volumes:
        # GPIO Anbindung
      - /sys/class/gpio/
        # Anbindung der 4 LED Lampen
      - /sys/class/leds/
