# This container will use BeagleBone Black GPIO

version: '3.8'

services:

  bbb_gpio_python:
    container_name: bbb_python
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - /dev/i2c-0 # P9 I2C PINs
      - /dev/i2c-1
      - /dev/i2c-2
    volumes:
      - /sys/class/gpio